name: digikam
version: '6.2.0'
summary:  Advanced digital photo management. 
description: Makes importing and organizing digital photos a 'snap'.
  
grade: stable
confinement: devmode
base: core18

architectures:
  - build-on: amd64
  

apps:
  digikam:
    command: bin/digikam
    plugs:
      - home
      - network
      - removable-media

parts:
digikam:
    plugin: 
    source: https://github.com/KDE/digikam.git
    source-type: git
    override-pull: |
     git clone https://github.com/KDE/digikam.git src/github.com/KDE/digikam
       cd src/github.com/KDE/digikam
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/KDE/digikam
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/KDE/digikam/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/KDE/digikam/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/digikam
        
    build-packages:
      - git
      - sed
      - g++
      - make
      - libsdl1.2-dev
      - libpng-dev
      - libsdl-net1.2-dev
      - libsdl-sound1.2-dev
      - libasound2-dev
      
    stage-packages:
      - libsdl-sound1.2
      - libsdl-net1.2
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libopenal1
      - libsndio6.1
      - libspeex1
      - libvorbisfile3
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libxkbcommon0
      - libglu1-mesa
      - libasound2
      - libasyncns0
      - libbsd0
      - libcaca0
      - libdbus-1-3
      - libflac8
      - libgcc1
      - libgcrypt20
      - libgl1
      - libglvnd0
      - libglx0
      - libgpg-error0
      - liblz4-1
      - liblzma5
      - libncursesw5
      - libogg0
      - libpng16-16
      - libpulse0
      - libsdl1.2debian
      - libslang2
      - libsndfile1
      - libstdc++6
      - libsystemd0
      - libtinfo5
      - libvorbis0a
      - libvorbisenc2
      - libwrap0
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - zlib1g
